### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by speedery** [some9000/StylePile#39] opened 2022-12-30 02:46 UTC
I encountered the following error while I was using Automatic1111 stable-diffusion -webui:

`FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/sd/stablediffusion/extensions/StylePile/StylePile/Directions/'`

I installed it through the extensions tab "Install from URL".

It seems the StylePile was downloaded in the folder "/stable-diffusion-webui/", while the script was looking for it in the folder "/stablediffusion/".

As a workaround for this issue, I duplicated the folder StylePile to the "/stablediffusion/" folder which worked for me.

Thank you.

**Comment by CriticalSteffen** [comment] 2023-03-09 21:58
I'm having this problem too. For me, the issue is that I'm running the webui from one folder, but storing data in a different folder (as defined by the `--data-dir` argument in `webui-user.sh`).

On [line 43 of StilePile.py](https://github.com/some9000/StylePile/blob/main/scripts/StylePile.py#L43), the script sets `file_dir` equal to the realpath of `__file__`. Unfortunately, this doesn't work as expected; rather than reading the path where `StylePyle.py` is stored on-disk, the `__file__` path points to the directory from which the [stable-diffusion-webui/launch.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/launch.py) script is executed.

As a result, StylePile fails to find its own files:

```
Error loading script: StylePile.py
Traceback (most recent call last):
  File "/home/username/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/username/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/path/to/sd/extensions/StylePile/scripts/StylePile.py", line 187, in <module>
    ResultDirectionList = FilesInFolder(ResourceDir + "Directions/")
  File "/path/to/sd/extensions/StylePile/scripts/StylePile.py", line 47, in FilesInFolder
    return [file for file in os.listdir(SourceFolder)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/stable-diffusion-webui/extensions/StylePile/StylePile/Directions/'
```

This breaks the extension.

**Comment by some9000** [comment] 2023-04-13 18:33
Sorry for the super late reply. I believe this has been fixed in the latest versions. I cannot really test with my folder setup.

**Closed by some9000** 2023-04-13 18:33 UTC
